-- ==============================================================================
-- 17_monitoring_tables.sql
-- Description: Physical schema for Alerting and Extended Observability
-- Phase: 08 - CDC Framework (Module 8)
-- ==============================================================================

USE ROLE SYSADMIN;
USE DATABASE DB_PROD_METADATA;

CREATE SCHEMA IF NOT EXISTS SC_META_OBSERVABILITY;
USE SCHEMA SC_META_OBSERVABILITY;

-- ------------------------------------------------------------------------------
-- 1. ALERT QUEUE TABLE
-- ------------------------------------------------------------------------------
-- Stores proactive alerts generated by the monitoring procedures before they 
-- are dispatched via external integrations (e.g., SNS, Slack, PagerDuty)
CREATE TABLE IF NOT EXISTS TB_ALERT_QUEUE (
    Alert_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    Alert_Type VARCHAR(50), -- PIPELINE_FAILURE, SLA_BREACH, CREDIT_SPIKE, STALE_STREAM
    Severity VARCHAR(20),   -- CRITICAL, HIGH, MEDIUM, LOW
    Pipeline_ID VARCHAR(50),
    Alert_Message VARCHAR,
    Is_Resolved BOOLEAN DEFAULT FALSE,
    Resolved_At TIMESTAMP_LTZ,
    Created_At TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ------------------------------------------------------------------------------
-- 2. PIPELINE EXECUTION HISTORY (Consolidated)
-- ------------------------------------------------------------------------------
-- Aggregates Snowpipe, Task, and Batch metrics into a single historical fact table
CREATE TABLE IF NOT EXISTS TB_PIPELINE_METRICS_HISTORY (
    Metric_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    Pipeline_ID VARCHAR(50),
    Execution_Date DATE,
    Total_Executions NUMBER,
    Failed_Executions NUMBER,
    Total_Rows_Extracted NUMBER,
    Total_Rows_Inserted NUMBER,
    Total_Rows_Updated NUMBER,
    Avg_Execution_Time_Seconds NUMBER,
    Max_Latency_Minutes NUMBER
);

-- ------------------------------------------------------------------------------
-- 3. DATA QUALITY (DQ) RESULTS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_DQ_RESULTS (
    Check_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    Target_Table VARCHAR(200),
    Rule_Name VARCHAR(100),
    Passed_Count NUMBER,
    Failed_Count NUMBER,
    Status VARCHAR(20),
    Executed_At TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
