{{
  config(
    materialized = 'incremental',
    unique_key = 'sales_sk',
    incremental_strategy = 'merge',
    cluster_by = ['date_sk'],
    on_schema_change = 'append_new_columns',
    tags = ['domain:ecommerce', 'layer:incremental']
  )
}}

/*
    MODEL PERFORMANCE NOTES:
    - Expected row counts: 100M+ per year
    - Incremental strategy: merge (Safely updates late-arriving sales)
    - Suggested cluster keys: date_sk
    - Estimated refresh frequency: 15-minute micro-batch tied to CDC Tasks
    - Downstream consumers: Executive Sales Dashboard
    - CDC Integration: Relies on `cdc_metadata_inserted_at` generated by Phase 08.
*/

with orders_enriched as (
    select * from {{ ref('int_orders_enriched') }}
),

final as (
    select
        {{ dbt_utils.generate_surrogate_key(['order_id', 'customer_id']) }} as sales_sk,
        cast(to_char(created_at_utc, 'YYYYMMDD') as integer) as date_sk,
        coalesce(customer_sk, {{ dbt_utils.generate_surrogate_key(['-1']) }}) as customer_sk,
        order_id as degenerate_order_id,
        coalesce(net_revenue_usd, 0) as net_revenue,
        coalesce(tax_price_usd, 0) as tax_amount,
        
        -- Audit & CDC Integration
        dbt_updated_at as cdc_metadata_inserted_at
        
    from orders_enriched
    
    -- Dynamically applies the sliding CDC watermark
    {{ generate_cdc_watermark(time_column='cdc_metadata_inserted_at', lookback_hours=24) }}
)

select * from final
